### ISSUE TITLE
make angular-accordion available for easy bower download

### ISSUE THREAD

**Issue by martinmuellerrohde** [uxman-sherwani/angular-accordion#21]
Hello,
using bower for dependency management I currently have to use something like

``` 
"ang-accordion": "git://github.com/sherwaniusman/angular-accordion.git"
``` 
It would be nice if you could start tagging your versions, so I could use

``` 
"ang-accordion": "1.0.0"
``` 
instead.
In addition it might be necessary to change the name in your bower.json to "ang-accordion" as this is where http://bower.io/search/ finds your great package.

Regards, Martin

**Comment by sherwaniusman** [comment]
Thank you for your input. Can you create a PR for this change?
