### ISSUE TITLE
ng-model for input text box not working 

### ISSUE THREAD

**Issue by GHR-Arash** [uxman-sherwani/angular-accordion#24]
i have input type="text " inside collapsible-item. it doens  bind to ng-model . 
outside  collapsible-item the text box is working perfectly .

**Comment by uxman-sherwani** [comment]
This directive has its own child scope, that's why the parent scope will not work inside the collapsible-item. 

Checkout this article about different types of scopes that you can pass with directives. http://www.undefinednull.com/2014/02/11/mastering-the-scope-of-a-directive-in-angularjs/
